#pragma config(Motor,  port1,           leftBack,      tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightFront,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightTop,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightBottom,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           middleRoller,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftBottom,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           leftTop,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           leftFront,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          rightBack,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int basePowerCalc(int input) {
	if (abs(input) < 50)
		return 0;
	if (input > 0)
		return 1.6494*(input - 50);
	return 1.6494*(input + 50);
}

basePowerCalc(vexRT[Ch1]);

task main() {
	bool x = false;
	bool y = false;
	int counter = 0;

	while (true) {
		wait1Msec(10);

		motor[middleRoller] = vexRT[Btn6U]*127;

		if (vexRT[Btn7D]) {
			if (y)
				x = false;
			else
				x = true;
		}
		else if (counter == 0) {
			counter = 25;
			if (x)
				y = true;
			else
				y = false;
		}
		else
			counter--;

		if (x){
			motor[rightTop] = -127;
			motor[rightBottom] = -127;
			motor[leftTop] = -127;
			motor[leftBottom] = -127;
		}
		else {
			motor[rightTop] = 0;
			motor[rightBottom] = 0;
			motor[leftTop] = 0;
			motor[leftBottom] = 0;
		}

		// BASE
		int lPower = basePowerCalc(vexRT[Ch3]) + basePowerCalc(vexRT[Ch1]);
		int rPower = basePowerCalc(vexRT[Ch3]) - basePowerCalc(vexRT[Ch1]);

		motor[leftFront]  = lPower;
		motor[leftBack]   = lPower;

		motor[rightFront] = rPower;
		motor[rightBack]  = rPower;
	}
}
